services:
  postgres:
    image: postgres:latest
    container_name: calculator-db
    environment:
      POSTGRES_USER: calculator
      POSTGRES_PASSWORD: passord123
      POSTGRES_DB: calculator_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
