services:
  mysql:
    image: mysql:latest
    container_name: finds-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test-user
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: finds_db  # Rettet fra MYSQL_DB
    ports:
      - "3306:3306"  # Rettet fra 5432 til 3306
    volumes:
      - mysql_volume:/var/lib/mysql
    restart: unless-stopped  # Sikrer at databasen restartes hvis den stopper

volumes:
  mysql_volume:
    driver: local
